Traceback (most recent call last):
  File "/home/codespace/.cache/pypoetry/virtualenvs/tarea-5-asies-gatVDPia-py3.10/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/codespace/.cache/pypoetry/virtualenvs/tarea-5-asies-gatVDPia-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/codespace/.cache/pypoetry/virtualenvs/tarea-5-asies-gatVDPia-py3.10/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/local/python/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/codespace/.cache/pypoetry/virtualenvs/tarea-5-asies-gatVDPia-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/codespace/.cache/pypoetry/virtualenvs/tarea-5-asies-gatVDPia-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/codespace/.cache/pypoetry/virtualenvs/tarea-5-asies-gatVDPia-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
solverToUse = pp.COIN_CMD(path="D:/2024-1/Herramientas cuantitativas/Tarea 5/bin/cbc.exe", msg=False) 
model.solve(solver=solverToUse);
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mPulpSolverError[0m                           Traceback (most recent call last)
Cell [0;32mIn[11], line 2[0m
[1;32m      1[0m solverToUse [38;5;241m=[39m pp[38;5;241m.[39mCOIN_CMD(path[38;5;241m=[39m[38;5;124m"[39m[38;5;124mD:/2024-1/Herramientas cuantitativas/Tarea 5/bin/cbc.exe[39m[38;5;124m"[39m, msg[38;5;241m=[39m[38;5;28;01mFalse[39;00m) 
[0;32m----> 2[0m [43mmodel[49m[38;5;241;43m.[39;49m[43msolve[49m[43m([49m[43msolver[49m[38;5;241;43m=[39;49m[43msolverToUse[49m[43m)[49m;

File [0;32m~/.cache/pypoetry/virtualenvs/tarea-5-asies-gatVDPia-py3.10/lib/python3.10/site-packages/pulp/pulp.py:1883[0m, in [0;36mLpProblem.solve[0;34m(self, solver, **kwargs)[0m
[1;32m   1881[0m [38;5;66;03m# time it[39;00m
[1;32m   1882[0m [38;5;28mself[39m[38;5;241m.[39mstartClock()
[0;32m-> 1883[0m status [38;5;241m=[39m [43msolver[49m[38;5;241;43m.[39;49m[43mactualSolve[49m[43m([49m[38;5;28;43mself[39;49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m   1884[0m [38;5;28mself[39m[38;5;241m.[39mstopClock()
[1;32m   1885[0m [38;5;28mself[39m[38;5;241m.[39mrestoreObjective(wasNone, dummyVar)

File [0;32m~/.cache/pypoetry/virtualenvs/tarea-5-asies-gatVDPia-py3.10/lib/python3.10/site-packages/pulp/apis/coin_api.py:112[0m, in [0;36mCOIN_CMD.actualSolve[0;34m(self, lp, **kwargs)[0m
[1;32m    110[0m [38;5;28;01mdef[39;00m [38;5;21mactualSolve[39m([38;5;28mself[39m, lp, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[1;32m    111[0m [38;5;250m    [39m[38;5;124;03m"""Solve a well formulated lp problem"""[39;00m
[0;32m--> 112[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43msolve_CBC[49m[43m([49m[43mlp[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m~/.cache/pypoetry/virtualenvs/tarea-5-asies-gatVDPia-py3.10/lib/python3.10/site-packages/pulp/apis/coin_api.py:121[0m, in [0;36mCOIN_CMD.solve_CBC[0;34m(self, lp, use_mps)[0m
[1;32m    119[0m [38;5;250m[39m[38;5;124;03m"""Solve a MIP problem using CBC"""[39;00m
[1;32m    120[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39mexecutable([38;5;28mself[39m[38;5;241m.[39mpath):
[0;32m--> 121[0m     [38;5;28;01mraise[39;00m PulpSolverError(
[1;32m    122[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mPulp: cannot execute [39m[38;5;132;01m{[39;00m[38;5;28mself[39m[38;5;241m.[39mpath[38;5;132;01m}[39;00m[38;5;124m cwd: [39m[38;5;132;01m{[39;00mos[38;5;241m.[39mgetcwd()[38;5;132;01m}[39;00m[38;5;124m"[39m
[1;32m    123[0m     )
[1;32m    124[0m tmpLp, tmpMps, tmpSol, tmpMst [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mcreate_tmp_files(
[1;32m    125[0m     lp[38;5;241m.[39mname, [38;5;124m"[39m[38;5;124mlp[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mmps[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124msol[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mmst[39m[38;5;124m"[39m
[1;32m    126[0m )
[1;32m    127[0m [38;5;28;01mif[39;00m use_mps:

[0;31mPulpSolverError[0m: Pulp: cannot execute D:/2024-1/Herramientas cuantitativas/Tarea 5/bin/cbc.exe cwd: /workspaces/Tarea-5_ASIES/tarea5

